//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLake.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatasetLog
    {
        public long LogId { get; set; }
        public string DatasetName { get; set; }
        public string DatasetURL { get; set; }
        public Nullable<System.DateTime> LastRunDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> IsComplete { get; set; }
        public string LogDescription { get; set; }
    }
}
