//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLake.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeatureGeoServeInfo
    {
        public int GeoServeId { get; set; }
        public string IdentificationCode { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string GeoServeCodeId { get; set; }
        public Nullable<int> DataReference { get; set; }
    }
}
