//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLake.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public string CodeTable { get; set; }
        public int StatausCode { get; set; }
        public string CodeShortDescription { get; set; }
        public string CodeDescription { get; set; }
    }
}
