//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLake.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class USZipCode
    {
        public string ZCTA5CE10 { get; set; }
        public string AFFGEOID10 { get; set; }
        public string GEOID10 { get; set; }
        public string ZIPCODE { get; set; }
        public Nullable<long> ALAND10 { get; set; }
        public Nullable<long> AWATER10 { get; set; }
        public System.Data.Entity.Spatial.DbGeometry Geom { get; set; }
    }
}
