//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLake.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeatherDataset
    {
        public long AllDatasetId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Datatype { get; set; }
        public string stations { get; set; }
        public string attributes { get; set; }
        public Nullable<long> value { get; set; }
        public Nullable<int> DataReference { get; set; }
    }
}
