//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLake.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeatherLocationCategory
    {
        public long LocationCatagoryId { get; set; }
        public string id { get; set; }
        public string name { get; set; }
        public Nullable<int> DataReference { get; set; }
        public Nullable<int> Checksumcheck { get; set; }
    }
}
