//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLake.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowRun
    {
        public int WorkflowRunID { get; set; }
        public int WorkflowDefinitionID { get; set; }
        public int Status { get; set; }
        public System.DateTime StartedOn { get; set; }
        public Nullable<System.DateTime> CompletedOn { get; set; }
        public bool HasErrors { get; set; }
        public string CutoffValue { get; set; }
        public Nullable<System.DateTime> CutoffDateTime { get; set; }
        public string RunGUID { get; set; }
    }
}
