//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLake.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowLog
    {
        public int WorkflowLogID { get; set; }
        public int WorkflowRunID { get; set; }
        public Nullable<int> WorkflowTaskID { get; set; }
        public int LogLevel { get; set; }
        public string Message { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string ExceptionType { get; set; }
        public string ExceptionJSON { get; set; }
    }
}
