//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLake.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowDefinition
    {
        public int WorkflowDefinitionID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Status { get; set; }
        public bool IsEnabled { get; set; }
        public Nullable<System.DateTime> StartAfter { get; set; }
        public Nullable<System.DateTime> EndBefore { get; set; }
        public string ScheduleJSON { get; set; }
        public bool IsSingleton { get; set; }
        public bool IsScheduled { get; set; }
        public string WorkflowDefinitionGUID { get; set; }
    }
}
